require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

inhibit_all_warnings!

target 'FlatListPro' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod "RNFlashList", path: "../../RNFlashList.podspec", testspecs: ['Tests'], inhibit_warnings: false

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if Gem::Version.new('12.4') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          # Ensure all pods are using the same deployment target
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'

          # Fix for Xcode 15 - https://github.com/facebook/react-native/issues/37748#issuecomment-1580589448
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        end
      end
    end
  end

end
